# Generated by Django 4.1 on 2022-08-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='img',
        ),
    ]
