# Generated by Django 4.1 on 2022-08-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='queue_position',
            field=models.IntegerField(default=0),
        ),
    ]
