# Generated by Django 4.1 on 2022-08-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_place_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'title', 'img_file')},
        ),
    ]
